dist: trusty
language: java
jdk: oraclejdk8

branches:
  only:
    - master
    - /^build\/.*$/
    - kubernetes_integration

cache:
  directories:
    - $HOME/.apt-cache
    - $HOME/.local
    - $HOME/.m2

env:
  global:
    - MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
    - CLJ_HTTP_ASYNC_POOL_TEST_DURATION_MULTIPLIER=5

before_install:
  - pyenv global 3.6
  - echo "Sudo-enabled build? ${TRAVIS_SUDO}"

matrix:
  allow_failures:
    - name: 'Cook Scheduler benchmark tests'

  fast_finish: true

  include:
    - name: 'Cook Scheduler, CLI, and JobClient unit tests'
      before_script:
        - ./cli/travis/setup.sh
        - cd scheduler && ./travis/setup.sh
      script:
        - echo VERSION && python -c 'import dateutil; print(dateutil.__version__)'
        - pushd ../jobclient && mvn test
        - popd && pushd ../cli && python -m pytest
        - popd && lein with-profile +test test :all-but-benchmark
