dist: trusty
language: java
jdk: oraclejdk8

branches:
  only: master

cache:
  directories:
    - $HOME/.apt-cache
    - $HOME/.local
    - $HOME/.m2

env:
  global:
    - MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
    - CLJ_HTTP_ASYNC_POOL_TEST_DURATION_MULTIPLIER=5

before_install:
  - pyenv global 3.6
  - echo "Sudo-enabled build? ${TRAVIS_SUDO}"

matrix:
  allow_failures:
    - env: NAME='Cook Scheduler benchmark tests'

  fast_finish: true

  include:
    - env: NAME='Cook Scheduler unit tests'
      before_script: cd scheduler && ./travis/setup.sh
      script: lein test :all-but-benchmark

    - env: NAME='Cook Scheduler integration tests with HTTP Basic Auth'
      services: docker
      install: sudo ./travis/install_mesos.sh
      before_script: cd integration && ./travis/prepare_integration.sh
      script: ./travis/run_integration.sh --auth=http-basic

    - env: NAME='Cook Scheduler integration tests with Cook Executor'
      services: docker
      install: sudo ./travis/install_mesos.sh
      before_script: cd integration && ./travis/prepare_integration.sh
      script: ./travis/run_integration.sh --executor=cook

    - env: NAME='Cook Scheduler Simulator tests'
      services: docker
      install: sudo ./travis/install_mesos.sh
      before_script: cd simulator && ./travis/prepare_simulation.sh
      script: ./travis/run_simulation.sh

    - env: NAME='Cook Scheduler benchmark tests'
      before_script: cd scheduler && lein with-profiles +test deps
      script: lein test :benchmark

    - env: NAME='Cook Executor tests'
      before_script: cd executor && ./travis/setup.sh
      script: ./travis/run_tests.sh

    - env: NAME='Cook JobClient unit tests'
      before_script: cd jobclient && mvn dependency:resolve
      script: mvn test
