language: java
jdk:
- oraclejdk8
services:
  - docker
before_install:
  - pyenv global 3.5.3
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
  - echo "deb https://repos.mesosphere.io/ubuntu/ trusty main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
  - sudo apt-get update -qq
  - sudo apt-get install mesos -y </dev/null
branches:
  only:
    - master
sudo: required
dist: trusty
env:
  global:
    - MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so
    - CLJ_HTTP_ASYNC_POOL_TEST_DURATION_MULTIPLIER=5
  matrix:
    - COOK_EXECUTOR='1' TEST_DIR=executor DEPS_CMD='pip install -e .[tests]' TEST_CMD='nosetests'
matrix:
    fast_finish: true
    allow_failures:
      - env: COOK_EXECUTOR='1' TEST_DIR=integration DEPS_CMD='travis/prepare_integration.sh' TEST_CMD='travis/run_integration.sh explicit'
before_script: bash -xc "pushd $TEST_DIR && $DEPS_CMD"
script: bash -xc "pushd $TEST_DIR && $TEST_CMD"
